// Copyright (c) Microsoft Corporation.
// Licensed under the MIT License.

use crate::test_tpm_backend as test_tpm;
use crate::test_tpm_backend::TestTpmPlatform;
use crate::test_tpm_backend::USE_LEGACY_PREPROVISIONED_STATE;
use crate::tpm_lib::*;
use std::time::Instant;
use tpm_protocol::TPM_AZURE_AIK_HANDLE;
use tpm_protocol::TPM_DEFAULT_AKCERT_SIZE;
use tpm_protocol::TPM_GUEST_SECRET_HANDLE;
use tpm_protocol::TPM_NV_INDEX_AIK_CERT;
use tpm_protocol::TPM_NV_INDEX_ATTESTATION_REPORT;
use tpm_protocol::TPM_NV_INDEX_MITIGATED;
use tpm_protocol::TPM_RSA_SRK_HANDLE;
use tpm_protocol::tpm20proto::AlgId;
use tpm_protocol::tpm20proto::AlgIdEnum;
use tpm_protocol::tpm20proto::CommandCodeEnum;
use tpm_protocol::tpm20proto::ReservedHandle;
use tpm_protocol::tpm20proto::ResponseCode;
use tpm_protocol::tpm20proto::TPM20_HT_PERSISTENT;
use tpm_protocol::tpm20proto::TPM20_RH_ENDORSEMENT;
use tpm_protocol::tpm20proto::TPM20_RH_OWNER;
use tpm_protocol::tpm20proto::TPM20_RH_PLATFORM;
use tpm_protocol::tpm20proto::TpmaNvBits;
use tpm_protocol::tpm20proto::TpmaObjectBits;
use tpm_protocol::tpm20proto::protocol::StartupType;
use tpm_protocol::tpm20proto::protocol::Tpm2bBuffer;
use tpm_protocol::tpm20proto::protocol::Tpm2bPublic;
use tpm_protocol::tpm20proto::protocol::TpmsRsaParams;
use tpm_protocol::tpm20proto::protocol::TpmtPublic;
use tpm_protocol::tpm20proto::protocol::TpmtRsaScheme;
use tpm_protocol::tpm20proto::protocol::TpmtSymDefObject;
use zerocopy::FromZeros;
use zerocopy::IntoBytes;

impl TpmEngine for TestTpmPlatform {
    fn execute_command(
        &mut self,
        command: &mut [u8],
        response: &mut [u8],
    ) -> Result<(), TpmEngineError> {
        TestTpmPlatform::execute_command(self, command, response)
            .map(|_| ())
            .map_err(TpmEngineError::from_error)
    }

    fn max_nv_index_size(&self) -> u16 {
        test_tpm::MAX_NV_INDEX_SIZE
    }
}

const TPM_AZURE_EK_HANDLE: ReservedHandle = ReservedHandle::new(TPM20_HT_PERSISTENT, 0x010001);
const AUTH_VALUE: u64 = 0x7766554433221100;

struct TestPlatformCallbacks {
    blob: Vec<u8>,
    time: Instant,
}

impl test_tpm::PlatformCallbacks for TestPlatformCallbacks {
    fn commit_nv_state(&mut self, state: &[u8]) -> test_tpm::DynResult<()> {
        self.blob = state.to_vec();
        Ok(())
    }

    fn get_crypt_random(&mut self, buf: &mut [u8]) -> test_tpm::DynResult<usize> {
        getrandom::fill(buf).expect("rng failure");
        Ok(buf.len())
    }

    fn monotonic_timer(&mut self) -> std::time::Duration {
        self.time.elapsed()
    }

    fn get_unique_value(&self) -> &'static [u8] {
        b"vtpm test"
    }
}

fn create_tpm_engine_helper() -> TpmEngineHelper<TestTpmPlatform> {
    let tpm_engine = TestTpmPlatform::initialize(
        Box::new(TestPlatformCallbacks {
            blob: Vec::new(),
            time: Instant::now(),
        }),
        test_tpm::InitKind::ColdInit,
    )
    .expect("failed to initialize TPM test backend");

    TpmEngineHelper {
        tpm_engine,
        reply_buffer: [0u8; 4096],
    }
}

fn restart_tpm_engine(
    tpm_engine_helper: &mut TpmEngineHelper<TestTpmPlatform>,
    clear_context: bool,
    initialize: bool,
) {
    if clear_context {
        let result = tpm_engine_helper.clear_tpm_platform_context();
        assert!(result.is_ok());
    }

    tpm_engine_helper
        .tpm_engine
        .reset(None)
        .expect("failed to reset TPM test backend");

    if initialize {
        let result = tpm_engine_helper.initialize_tpm_engine();
        assert!(result.is_ok());
    }
}

fn initialize_pre_provisioned_tpm(tpm_engine_helper: &mut TpmEngineHelper<TestTpmPlatform>) {
    if USE_LEGACY_PREPROVISIONED_STATE {
        // The blob file generated by the TpmEngFWInit (internal) tool.
        let tpm_state_blob = include_bytes!("../../../test_data/vTpmState.blob");
        tpm_engine_helper
            .tpm_engine
            .reset(Some(tpm_state_blob))
            .expect("failed to load pre-provisioned TPM state");
    } else {
        // The checked-in TPM 1.38 NVRAM blob is not compatible with TPM 1.85.
        const PRE_PROVISIONED_AK_CERT: [u8; 1024] = [6; 1024];

        let result = tpm_engine_helper.initialize_tpm_engine();
        assert!(result.is_ok(), "{result:?}");

        let result = tpm_engine_helper.create_ak_pub(false);
        assert!(result.is_ok(), "{result:?}");

        let result = tpm_engine_helper.nv_define_space(
            TPM20_RH_OWNER,
            0,
            TPM_NV_INDEX_AIK_CERT,
            PRE_PROVISIONED_AK_CERT.len() as u16,
        );
        assert!(result.is_ok(), "{result:?}");

        let result = tpm_engine_helper.nv_write(
            TPM20_RH_OWNER,
            None,
            TPM_NV_INDEX_AIK_CERT,
            &PRE_PROVISIONED_AK_CERT,
        );
        assert!(result.is_ok(), "{result:?}");

        let template = rsa_srk_template().expect("failed to create SRK template");
        let srk = tpm_engine_helper
            .create_primary(TPM20_RH_OWNER, template)
            .expect("failed to create SRK");

        let result =
            tpm_engine_helper.evict_control(TPM20_RH_OWNER, srk.object_handle, TPM_RSA_SRK_HANDLE);
        assert!(result.is_ok(), "{result:?}");

        let result = tpm_engine_helper.flush_context(srk.object_handle);
        assert!(result.is_ok(), "{result:?}");

        tpm_engine_helper
            .tpm_engine
            .reset(None)
            .expect("failed to reset TPM test backend");
    }

    let result = tpm_engine_helper.initialize_tpm_engine();
    assert!(result.is_ok(), "{result:?}");
}

#[test]
fn test_create_ak_ek_pub() {
    let mut tpm_engine_helper = create_tpm_engine_helper();
    restart_tpm_engine(&mut tpm_engine_helper, false, true);

    // Test creating AK and EK

    // Ensure nothing present
    assert!(
        tpm_engine_helper
            .find_object(TPM_AZURE_AIK_HANDLE)
            .unwrap()
            .is_none()
    );
    assert!(
        tpm_engine_helper
            .find_object(TPM_AZURE_EK_HANDLE)
            .unwrap()
            .is_none()
    );

    let (ak_pub_first, ek_pub_first) = create_ak_ek_pub(&mut tpm_engine_helper);

    // Test creating AK and EK with clearing context

    restart_tpm_engine(&mut tpm_engine_helper, true, true);

    // Ensure nothing present after context is cleared and tpm reset
    assert!(
        tpm_engine_helper
            .find_object(TPM_AZURE_AIK_HANDLE)
            .unwrap()
            .is_none()
    );
    assert!(
        tpm_engine_helper
            .find_object(TPM_AZURE_EK_HANDLE)
            .unwrap()
            .is_none()
    );

    let (ak_pub_second, ek_pub_second) = create_ak_ek_pub(&mut tpm_engine_helper);

    // Ensure AK and EK match across reset if seeds do not change
    assert_eq!(ak_pub_first, ak_pub_second);
    assert_eq!(ek_pub_first, ek_pub_second);

    // Test creating AK and EK without clearing context and force_create = false

    restart_tpm_engine(&mut tpm_engine_helper, false, true);

    // Ensure that AK is persisted across reset without clearing context
    assert!(
        tpm_engine_helper
            .find_object(TPM_AZURE_AIK_HANDLE)
            .unwrap()
            .is_some()
    );
    assert!(
        tpm_engine_helper
            .find_object(TPM_AZURE_EK_HANDLE)
            .unwrap()
            .is_none()
    );

    let (ak_pub_third, ek_pub_third) = create_ak_ek_pub(&mut tpm_engine_helper);

    // Ensure AK and EK match across reset if seeds do not change
    assert_eq!(ak_pub_second, ak_pub_third);
    assert_eq!(ek_pub_second, ek_pub_third);

    // Test creating AK and EK without clearing context and force_create = true

    restart_tpm_engine(&mut tpm_engine_helper, false, true);

    // Ensure that AK is persisted across reset without clearing context
    assert!(
        tpm_engine_helper
            .find_object(TPM_AZURE_AIK_HANDLE)
            .unwrap()
            .is_some()
    );
    assert!(
        tpm_engine_helper
            .find_object(TPM_AZURE_EK_HANDLE)
            .unwrap()
            .is_none()
    );

    let (ak_pub_fourth, ek_pub_fourth) = create_ak_ek_pub(&mut tpm_engine_helper);

    // Ensure AK and EK match across reset if seeds do not change
    assert_eq!(ak_pub_third, ak_pub_fourth);
    assert_eq!(ek_pub_third, ek_pub_fourth);

    // Test creating AK and EK after refreshing TPM seeds

    restart_tpm_engine(&mut tpm_engine_helper, false, true);

    let result = tpm_engine_helper.refresh_tpm_seeds();
    assert!(result.is_ok());

    // Ensure nothing present after seeds refreshment
    assert!(
        tpm_engine_helper
            .find_object(TPM_AZURE_AIK_HANDLE)
            .unwrap()
            .is_none()
    );
    assert!(
        tpm_engine_helper
            .find_object(TPM_AZURE_EK_HANDLE)
            .unwrap()
            .is_none()
    );

    let (ak_pub_fifth, ek_pub_fifth) = create_ak_ek_pub(&mut tpm_engine_helper);

    // Ensure AK and EK mismatch across reset if seeds do change
    assert_ne!(ak_pub_fourth, ak_pub_fifth);
    assert_ne!(ek_pub_fourth, ek_pub_fifth);
}

fn create_ak_ek_pub(
    tpm_engine_helper: &mut TpmEngineHelper<TestTpmPlatform>,
) -> (TpmRsa2kPublic, TpmRsa2kPublic) {
    let result = tpm_engine_helper.create_ak_pub(false);
    assert!(result.is_ok());
    let (ak_pub, _) = result.unwrap();

    // Ensure `create_ak_pub` persists AK
    assert!(
        tpm_engine_helper
            .find_object(TPM_AZURE_AIK_HANDLE)
            .unwrap()
            .is_some()
    );
    assert!(
        tpm_engine_helper
            .find_object(TPM_AZURE_EK_HANDLE)
            .unwrap()
            .is_none()
    );

    let result = tpm_engine_helper.create_ek_pub();
    assert!(result.is_ok());
    let ek_pub = result.unwrap();

    // Ensure `create_ek_pub` does not persist anything
    assert!(
        tpm_engine_helper
            .find_object(TPM_AZURE_AIK_HANDLE)
            .unwrap()
            .is_some()
    );
    assert!(
        tpm_engine_helper
            .find_object(TPM_AZURE_EK_HANDLE)
            .unwrap()
            .is_none()
    );

    (ak_pub, ek_pub)
}

#[test]
fn test_allocate_guest_attestation_nv_indices() {
    const AK_CERT_INPUT_512: [u8; 512] = [7u8; 512];
    const AK_CERT_INPUT_1024: [u8; 1024] = [8u8; 1024];
    const ATTESTATION_REPORT_INPUT: [u8; 256] = [6u8; 256];

    let mut tpm_engine_helper = create_tpm_engine_helper();
    restart_tpm_engine(&mut tpm_engine_helper, false, true);

    // Test allocation without initial states and with with preserve_ak_cert = true, support_attestation_report = false
    // Expect only the ak cert nv index to be created but with no data
    // Do not write AK cert data to index after allocation.
    {
        let mut ak_cert_output = [0u8; TPM_DEFAULT_AKCERT_SIZE];
        let mut attestation_report_output = [0u8; MAX_ATTESTATION_INDEX_SIZE as usize];

        // Ensure both nv indices are not present
        let result =
            tpm_engine_helper.read_from_nv_index(TPM_NV_INDEX_AIK_CERT, &mut ak_cert_output);
        assert!(matches!(result.unwrap(), NvIndexState::Unallocated));

        let result = tpm_engine_helper.read_from_nv_index(
            TPM_NV_INDEX_ATTESTATION_REPORT,
            &mut attestation_report_output,
        );
        assert!(matches!(result.unwrap(), NvIndexState::Unallocated));

        restart_tpm_engine(&mut tpm_engine_helper, true, true);

        let result = tpm_engine_helper.allocate_guest_attestation_nv_indices(
            AUTH_VALUE,
            AllocateNvIndicesParams {
                preserve_ak_cert: true,
                support_attestation_report: false,
                mitigate_legacy_akcert: false,
                create_if_missing: true,
            },
        );
        assert!(result.is_ok());

        // Ensure ak cert nv index becomes uninitialized
        let result =
            tpm_engine_helper.read_from_nv_index(TPM_NV_INDEX_AIK_CERT, &mut ak_cert_output);
        assert!(matches!(result.unwrap(), NvIndexState::Uninitialized));

        let result = tpm_engine_helper.read_from_nv_index(
            TPM_NV_INDEX_ATTESTATION_REPORT,
            &mut attestation_report_output,
        );
        assert!(matches!(result.unwrap(), NvIndexState::Unallocated));
    }

    // Test allocation without initial states and with with preserve_ak_cert = true, support_attestation_report = false
    // Expect only the ak cert nv index to be created but with no data
    // Write AK cert data to index after allocation.
    {
        let mut ak_cert_output = [0u8; TPM_DEFAULT_AKCERT_SIZE];
        let mut attestation_report_output = [0u8; MAX_ATTESTATION_INDEX_SIZE as usize];

        restart_tpm_engine(&mut tpm_engine_helper, true, true);

        // Ensure only ak cert index is present but uninitialized after reboot
        let result =
            tpm_engine_helper.read_from_nv_index(TPM_NV_INDEX_AIK_CERT, &mut ak_cert_output);
        assert!(matches!(result.unwrap(), NvIndexState::Uninitialized));

        let result = tpm_engine_helper.read_from_nv_index(
            TPM_NV_INDEX_ATTESTATION_REPORT,
            &mut attestation_report_output,
        );
        assert!(matches!(result.unwrap(), NvIndexState::Unallocated));

        let result = tpm_engine_helper.allocate_guest_attestation_nv_indices(
            AUTH_VALUE,
            AllocateNvIndicesParams {
                preserve_ak_cert: true,
                support_attestation_report: false,
                mitigate_legacy_akcert: false,
                create_if_missing: true,
            },
        );
        assert!(result.is_ok());

        // Ensure only ak cert index remains present but uninitialized
        let result =
            tpm_engine_helper.read_from_nv_index(TPM_NV_INDEX_AIK_CERT, &mut ak_cert_output);
        assert!(matches!(result.unwrap(), NvIndexState::Uninitialized));

        let result = tpm_engine_helper.read_from_nv_index(
            TPM_NV_INDEX_ATTESTATION_REPORT,
            &mut attestation_report_output,
        );
        assert!(matches!(result.unwrap(), NvIndexState::Unallocated));

        // Write to ak cert nv
        let result = tpm_engine_helper.write_to_nv_index(
            AUTH_VALUE,
            TPM_NV_INDEX_AIK_CERT,
            &AK_CERT_INPUT_512,
        );
        assert!(result.is_ok());

        // Read the data and ensure it is zero-padded
        let result =
            tpm_engine_helper.read_from_nv_index(TPM_NV_INDEX_AIK_CERT, &mut ak_cert_output);
        assert!(matches!(result.unwrap(), NvIndexState::Available));
        let input_with_padding = {
            let mut input = AK_CERT_INPUT_512.to_vec();
            input.resize(TPM_DEFAULT_AKCERT_SIZE, 0);
            input
        };
        assert_eq!(&ak_cert_output, input_with_padding.as_slice());
    }

    // Test allocation after a restart with preserve_ak_cert = true, support_attestation_report = false
    // Expect the content of ak cert nv index to be re-created and the ak cert is preserved
    {
        let mut ak_cert_output = [0u8; TPM_DEFAULT_AKCERT_SIZE];
        let mut attestation_report_output = [0u8; MAX_ATTESTATION_INDEX_SIZE as usize];

        restart_tpm_engine(&mut tpm_engine_helper, true, true);

        // Ensure only ak cert index remains available after reboot
        let result =
            tpm_engine_helper.read_from_nv_index(TPM_NV_INDEX_AIK_CERT, &mut ak_cert_output);
        assert!(matches!(result.unwrap(), NvIndexState::Available));

        let result = tpm_engine_helper.read_from_nv_index(
            TPM_NV_INDEX_ATTESTATION_REPORT,
            &mut attestation_report_output,
        );
        assert!(matches!(result.unwrap(), NvIndexState::Unallocated));

        let result = tpm_engine_helper.allocate_guest_attestation_nv_indices(
            AUTH_VALUE,
            AllocateNvIndicesParams {
                preserve_ak_cert: true,
                support_attestation_report: false,
                mitigate_legacy_akcert: false,
                create_if_missing: true,
            },
        );
        assert!(result.is_ok());

        // Ensure only ak cert index remains available
        let result =
            tpm_engine_helper.read_from_nv_index(TPM_NV_INDEX_AIK_CERT, &mut ak_cert_output);
        assert!(matches!(result.unwrap(), NvIndexState::Available));

        let result = tpm_engine_helper.read_from_nv_index(
            TPM_NV_INDEX_ATTESTATION_REPORT,
            &mut attestation_report_output,
        );
        assert!(matches!(result.unwrap(), NvIndexState::Unallocated));

        // Read the data and ensure it is zero-padded
        let result =
            tpm_engine_helper.read_from_nv_index(TPM_NV_INDEX_AIK_CERT, &mut ak_cert_output);
        assert!(matches!(result.unwrap(), NvIndexState::Available));
        let input_with_padding = {
            let mut input = AK_CERT_INPUT_512.to_vec();
            input.resize(TPM_DEFAULT_AKCERT_SIZE, 0);
            input
        };
        assert_eq!(&ak_cert_output, input_with_padding.as_slice());

        // Write to ak cert nv
        let result = tpm_engine_helper.write_to_nv_index(
            AUTH_VALUE,
            TPM_NV_INDEX_AIK_CERT,
            &AK_CERT_INPUT_1024,
        );
        assert!(result.is_ok());

        // Read the data and ensure it is zero-padded
        let result =
            tpm_engine_helper.read_from_nv_index(TPM_NV_INDEX_AIK_CERT, &mut ak_cert_output);
        assert!(matches!(result.unwrap(), NvIndexState::Available));
        let input_with_padding = {
            let mut input = AK_CERT_INPUT_1024.to_vec();
            input.resize(TPM_DEFAULT_AKCERT_SIZE, 0);
            input
        };
        assert_eq!(&ak_cert_output, input_with_padding.as_slice());
    }

    // Test allocation after a restart with preserve_ak_cert = false, support_attestation_report = false
    // Expect ak cert nv index to be re-created and the ak cert is not preserved
    {
        let mut ak_cert_output = [0u8; TPM_DEFAULT_AKCERT_SIZE];
        let mut attestation_report_output = [0u8; MAX_ATTESTATION_INDEX_SIZE as usize];

        restart_tpm_engine(&mut tpm_engine_helper, true, true);

        // Ensure only ak cert index remains available after reboot
        let result =
            tpm_engine_helper.read_from_nv_index(TPM_NV_INDEX_AIK_CERT, &mut ak_cert_output);
        assert!(matches!(result.unwrap(), NvIndexState::Available));

        let result = tpm_engine_helper.read_from_nv_index(
            TPM_NV_INDEX_ATTESTATION_REPORT,
            &mut attestation_report_output,
        );
        assert!(matches!(result.unwrap(), NvIndexState::Unallocated));

        let result = tpm_engine_helper.allocate_guest_attestation_nv_indices(
            AUTH_VALUE,
            AllocateNvIndicesParams {
                preserve_ak_cert: false,
                support_attestation_report: false,
                mitigate_legacy_akcert: false,
                create_if_missing: true,
            },
        );
        assert!(result.is_ok());

        // Ensure read to fail given that the ak cert index is re-created and data is not preserved
        let result =
            tpm_engine_helper.read_from_nv_index(TPM_NV_INDEX_AIK_CERT, &mut ak_cert_output);
        assert!(matches!(result.unwrap(), NvIndexState::Uninitialized));

        let result = tpm_engine_helper.read_from_nv_index(
            TPM_NV_INDEX_ATTESTATION_REPORT,
            &mut attestation_report_output,
        );
        assert!(matches!(result.unwrap(), NvIndexState::Unallocated));

        // Write to ak cert nv
        let result = tpm_engine_helper.write_to_nv_index(
            AUTH_VALUE,
            TPM_NV_INDEX_AIK_CERT,
            &AK_CERT_INPUT_512,
        );
        assert!(result.is_ok());

        // Read the data and ensure it is zero-padded
        let result =
            tpm_engine_helper.read_from_nv_index(TPM_NV_INDEX_AIK_CERT, &mut ak_cert_output);
        assert!(matches!(result.unwrap(), NvIndexState::Available));
        let input_with_padding = {
            let mut input = AK_CERT_INPUT_512.to_vec();
            input.resize(TPM_DEFAULT_AKCERT_SIZE, 0);
            input
        };
        assert_eq!(&ak_cert_output, input_with_padding.as_slice());
    }

    // Test allocation after a restart preserve_ak_cert = false, support_attestation_report = true
    // Expect ak cert nv index to be re-created and attestation report nv index to be created
    {
        let mut ak_cert_output = [0u8; TPM_DEFAULT_AKCERT_SIZE];
        let mut attestation_report_output = [0u8; MAX_ATTESTATION_INDEX_SIZE as usize];

        restart_tpm_engine(&mut tpm_engine_helper, true, true);

        // Ensure the state of indices remains the same after reboot
        let result =
            tpm_engine_helper.read_from_nv_index(TPM_NV_INDEX_AIK_CERT, &mut ak_cert_output);
        assert!(matches!(result.unwrap(), NvIndexState::Available));

        let result = tpm_engine_helper.read_from_nv_index(
            TPM_NV_INDEX_ATTESTATION_REPORT,
            &mut attestation_report_output,
        );
        assert!(matches!(result.unwrap(), NvIndexState::Unallocated));

        let result = tpm_engine_helper.allocate_guest_attestation_nv_indices(
            AUTH_VALUE,
            AllocateNvIndicesParams {
                preserve_ak_cert: false,
                support_attestation_report: true,
                mitigate_legacy_akcert: false,
                create_if_missing: true,
            },
        );
        assert!(result.is_ok());

        // Ensure read to fail given that the ak cert index is re-created and data is not preserved
        let result =
            tpm_engine_helper.read_from_nv_index(TPM_NV_INDEX_AIK_CERT, &mut ak_cert_output);
        assert!(matches!(result.unwrap(), NvIndexState::Uninitialized));

        // Ensure read to fail given that the report index is created but uninitialized
        let result = tpm_engine_helper.read_from_nv_index(
            TPM_NV_INDEX_ATTESTATION_REPORT,
            &mut attestation_report_output,
        );
        assert!(matches!(result.unwrap(), NvIndexState::Uninitialized));

        // Write to ak cert nv
        let result = tpm_engine_helper.write_to_nv_index(
            AUTH_VALUE,
            TPM_NV_INDEX_AIK_CERT,
            &AK_CERT_INPUT_512,
        );
        assert!(result.is_ok());

        // Read the data and ensure it is zero-padded
        let result =
            tpm_engine_helper.read_from_nv_index(TPM_NV_INDEX_AIK_CERT, &mut ak_cert_output);
        assert!(matches!(result.unwrap(), NvIndexState::Available));
        let input_with_padding = {
            let mut input = AK_CERT_INPUT_512.to_vec();
            input.resize(TPM_DEFAULT_AKCERT_SIZE, 0);
            input
        };
        assert_eq!(&ak_cert_output, input_with_padding.as_slice());

        // Write to attestation report nv
        let result = tpm_engine_helper.write_to_nv_index(
            AUTH_VALUE,
            TPM_NV_INDEX_ATTESTATION_REPORT,
            &ATTESTATION_REPORT_INPUT,
        );
        assert!(result.is_ok());

        // Read the data and ensure it is zero-padded
        let result = tpm_engine_helper.read_from_nv_index(
            TPM_NV_INDEX_ATTESTATION_REPORT,
            &mut attestation_report_output,
        );
        assert!(matches!(result.unwrap(), NvIndexState::Available));
        let input_with_padding = {
            let mut input = ATTESTATION_REPORT_INPUT.to_vec();
            input.resize(MAX_ATTESTATION_INDEX_SIZE.into(), 0);
            input
        };
        assert_eq!(&attestation_report_output, input_with_padding.as_slice());
    }

    // Test allocation after a restart preserve_ak_cert = false, support_attestation_report = true
    // Expect both ak cert and attestation report nv indices to be re-created
    {
        let mut ak_cert_output = [0u8; TPM_DEFAULT_AKCERT_SIZE];
        let mut attestation_report_output = [0u8; MAX_ATTESTATION_INDEX_SIZE as usize];

        restart_tpm_engine(&mut tpm_engine_helper, true, true);

        // Ensure the state of indices remains the same after reboot
        let result =
            tpm_engine_helper.read_from_nv_index(TPM_NV_INDEX_AIK_CERT, &mut ak_cert_output);
        assert!(matches!(result.unwrap(), NvIndexState::Available));

        let result = tpm_engine_helper.read_from_nv_index(
            TPM_NV_INDEX_ATTESTATION_REPORT,
            &mut attestation_report_output,
        );
        assert!(matches!(result.unwrap(), NvIndexState::Available));

        let result = tpm_engine_helper.allocate_guest_attestation_nv_indices(
            AUTH_VALUE,
            AllocateNvIndicesParams {
                preserve_ak_cert: false,
                support_attestation_report: true,
                mitigate_legacy_akcert: false,
                create_if_missing: true,
            },
        );
        assert!(result.is_ok());

        // Expect read to return Ok(false) given that the nv index is re-created and data is not preserved
        let result =
            tpm_engine_helper.read_from_nv_index(TPM_NV_INDEX_AIK_CERT, &mut ak_cert_output);
        assert!(matches!(result.unwrap(), NvIndexState::Uninitialized));

        // Expect read to return Ok(false) given that the nv index is re-created and no data has been written
        let result = tpm_engine_helper.read_from_nv_index(
            TPM_NV_INDEX_ATTESTATION_REPORT,
            &mut attestation_report_output,
        );
        assert!(matches!(result.unwrap(), NvIndexState::Uninitialized));
    }
}

#[test]
fn test_read_write_guest_attestation_indices() {
    let mut tpm_engine_helper = create_tpm_engine_helper();
    restart_tpm_engine(&mut tpm_engine_helper, false, true);

    let result = tpm_engine_helper.allocate_guest_attestation_nv_indices(
        AUTH_VALUE,
        AllocateNvIndicesParams {
            preserve_ak_cert: true,
            support_attestation_report: true,
            mitigate_legacy_akcert: false,
            create_if_missing: true,
        },
    );
    assert!(result.is_ok());

    let result = tpm_engine_helper.find_nv_index(TPM_NV_INDEX_AIK_CERT);
    assert!(result.is_ok());
    assert!(result.unwrap().is_some());

    let result = tpm_engine_helper.find_nv_index(TPM_NV_INDEX_ATTESTATION_REPORT);
    assert!(result.is_ok());
    assert!(result.unwrap().is_some());

    // Test writing to ak cert nv index with data size equal to index size
    {
        let ak_cert_input_equal = [7u8; TPM_DEFAULT_AKCERT_SIZE];
        let result = tpm_engine_helper.write_to_nv_index(
            AUTH_VALUE,
            TPM_NV_INDEX_AIK_CERT,
            &ak_cert_input_equal,
        );
        assert!(result.is_ok());

        let mut ak_cert_output = [0u8; TPM_DEFAULT_AKCERT_SIZE];
        let result =
            tpm_engine_helper.read_from_nv_index(TPM_NV_INDEX_AIK_CERT, &mut ak_cert_output);
        assert!(result.is_ok());
        assert_eq!(&ak_cert_output, &ak_cert_input_equal);
    }

    // Test writing to ak cert nv index with data size less than index size
    {
        let ak_cert_input_less = [7u8; TPM_DEFAULT_AKCERT_SIZE - 1024];
        let result = tpm_engine_helper.write_to_nv_index(
            AUTH_VALUE,
            TPM_NV_INDEX_AIK_CERT,
            &ak_cert_input_less,
        );
        assert!(result.is_ok());

        // Read the data and ensure it is zero-padded
        let mut ak_cert_output = [0u8; TPM_DEFAULT_AKCERT_SIZE];
        let result =
            tpm_engine_helper.read_from_nv_index(TPM_NV_INDEX_AIK_CERT, &mut ak_cert_output);
        assert!(result.is_ok());
        let input_with_padding = {
            let mut input = ak_cert_input_less.to_vec();
            input.resize(TPM_DEFAULT_AKCERT_SIZE, 0);
            input
        };
        assert_eq!(&ak_cert_output, input_with_padding.as_slice());
    }

    // Test writing to ak cert nv index with data size larger than index size
    {
        let ak_cert_input_larger = [7u8; TPM_DEFAULT_AKCERT_SIZE + 1024];
        let result = tpm_engine_helper.write_to_nv_index(
            AUTH_VALUE,
            TPM_NV_INDEX_AIK_CERT,
            &ak_cert_input_larger,
        );
        assert!(result.is_err());
        let err = result.unwrap_err();
        if let Error::NvWriteInputTooLarge {
            nv_index,
            input_size,
            allocated_size,
        } = err
        {
            assert_eq!(nv_index, TPM_NV_INDEX_AIK_CERT);
            assert_eq!(input_size, ak_cert_input_larger.len());
            assert_eq!(allocated_size, TPM_DEFAULT_AKCERT_SIZE);
        } else {
            panic!()
        }
    }

    // Test writing to ak cert nv index with wrong authorization value
    {
        let ak_cert_input_larger = [7u8; TPM_DEFAULT_AKCERT_SIZE];
        let result =
            tpm_engine_helper.write_to_nv_index(0, TPM_NV_INDEX_AIK_CERT, &ak_cert_input_larger);
        assert!(result.is_err());
        let err = result.unwrap_err();
        if let Error::TpmCommandError {
            command_debug_info,
            error: command_error,
        } = err
        {
            assert_eq!(command_debug_info.nv_index, Some(TPM_NV_INDEX_AIK_CERT));
            assert_eq!(
                command_debug_info.auth_handle,
                Some(ReservedHandle(TPM_NV_INDEX_AIK_CERT.into()))
            );
            assert_eq!(command_debug_info.command_code, CommandCodeEnum::NV_Write);
            assert!(matches!(
                command_error,
                TpmCommandError::TpmCommandFailed { response_code: _ }
            ));
        }
    }

    // Test writing to attestation report nv index with data size equal to index size
    {
        let report_input_equal = [7u8; MAX_ATTESTATION_INDEX_SIZE as usize];
        let result = tpm_engine_helper.write_to_nv_index(
            AUTH_VALUE,
            TPM_NV_INDEX_ATTESTATION_REPORT,
            &report_input_equal,
        );
        assert!(result.is_ok());

        let mut report_output = [0u8; MAX_ATTESTATION_INDEX_SIZE as usize];
        let result = tpm_engine_helper
            .read_from_nv_index(TPM_NV_INDEX_ATTESTATION_REPORT, &mut report_output);
        assert!(result.is_ok());
        assert_eq!(&report_output, &report_input_equal);
    }

    // Test writing to attestation report nv index with data size less than index size
    {
        let report_input_less = [7u8; MAX_ATTESTATION_INDEX_SIZE as usize - 1024];
        let result = tpm_engine_helper.write_to_nv_index(
            AUTH_VALUE,
            TPM_NV_INDEX_ATTESTATION_REPORT,
            &report_input_less,
        );
        assert!(result.is_ok());

        // Read the data and ensure it is zero-padded
        let mut report_output = [0u8; MAX_ATTESTATION_INDEX_SIZE as usize];
        let result = tpm_engine_helper
            .read_from_nv_index(TPM_NV_INDEX_ATTESTATION_REPORT, &mut report_output);
        assert!(result.is_ok());
        let input_with_padding = {
            let mut input = report_input_less.to_vec();
            input.resize(MAX_ATTESTATION_INDEX_SIZE.into(), 0);
            input
        };
        assert_eq!(&report_output, input_with_padding.as_slice());
    }

    // Test writing to attestation report nv index with data size larger than index size
    {
        let report_input_larger = [7u8; MAX_ATTESTATION_INDEX_SIZE as usize + 1024];
        let result = tpm_engine_helper.write_to_nv_index(
            AUTH_VALUE,
            TPM_NV_INDEX_ATTESTATION_REPORT,
            &report_input_larger,
        );
        assert!(result.is_err());
        let err = result.unwrap_err();
        if let Error::NvWriteInputTooLarge {
            nv_index,
            input_size,
            allocated_size,
        } = err
        {
            assert_eq!(nv_index, TPM_NV_INDEX_ATTESTATION_REPORT);
            assert_eq!(input_size, report_input_larger.len());
            assert_eq!(allocated_size, MAX_ATTESTATION_INDEX_SIZE as usize);
        }
    }

    // Test writing to attestation report nv index with wrong authorization value
    {
        let ak_cert_input_larger = [7u8; TPM_DEFAULT_AKCERT_SIZE];
        let result = tpm_engine_helper.write_to_nv_index(
            0,
            TPM_NV_INDEX_ATTESTATION_REPORT,
            &ak_cert_input_larger,
        );
        assert!(result.is_err());
        let err = result.unwrap_err();
        if let Error::TpmCommandError {
            command_debug_info,
            error: command_error,
        } = err
        {
            assert_eq!(
                command_debug_info.nv_index,
                Some(TPM_NV_INDEX_ATTESTATION_REPORT)
            );
            assert_eq!(
                command_debug_info.auth_handle,
                Some(ReservedHandle(TPM_NV_INDEX_ATTESTATION_REPORT.into()))
            );
            assert_eq!(command_debug_info.command_code, CommandCodeEnum::NV_Write);
            assert!(matches!(
                command_error,
                TpmCommandError::TpmCommandFailed { response_code: _ }
            ));
        }
    }
}

#[test]
fn test_with_pre_provisioned_state() {
    let mut tpm_engine_helper = create_tpm_engine_helper();
    initialize_pre_provisioned_tpm(&mut tpm_engine_helper);

    // Ensure AK cert is provisioned
    let result = tpm_engine_helper.nv_read_public(TPM_NV_INDEX_AIK_CERT);
    assert!(result.is_ok());
    let nv_read_public_reply = result.unwrap();

    // The provisioned nv size is less than the created one
    let nv_size = nv_read_public_reply.nv_public.nv_public.data_size.get();
    assert!((nv_size as usize) < TPM_DEFAULT_AKCERT_SIZE);

    // Ensure AK is provisioned
    assert!(
        tpm_engine_helper
            .find_object(TPM_AZURE_AIK_HANDLE)
            .unwrap()
            .is_some()
    );

    let mut provisioned_ak_cert = [0u8; TPM_DEFAULT_AKCERT_SIZE];
    let result =
        tpm_engine_helper.read_from_nv_index(TPM_NV_INDEX_AIK_CERT, &mut provisioned_ak_cert);
    assert!(matches!(result.unwrap(), NvIndexState::Available));

    // Ensure allocate_guest_attestation_nv_indices with preserve_ak_cert = true preserves the ak cert data
    let result = tpm_engine_helper.allocate_guest_attestation_nv_indices(
        AUTH_VALUE,
        AllocateNvIndicesParams {
            preserve_ak_cert: true,
            support_attestation_report: false,
            mitigate_legacy_akcert: false,
            create_if_missing: true,
        },
    );
    assert!(result.is_ok());

    // Ensure nv index has the same size
    let result = tpm_engine_helper.nv_read_public(TPM_NV_INDEX_AIK_CERT);
    assert!(result.is_ok());
    let nv_read_public_reply = result.unwrap();
    assert!(nv_read_public_reply.nv_public.nv_public.data_size.get() == nv_size);

    let mut provisioned_ak_cert_after_call = [0u8; TPM_DEFAULT_AKCERT_SIZE];
    let result = tpm_engine_helper
        .read_from_nv_index(TPM_NV_INDEX_AIK_CERT, &mut provisioned_ak_cert_after_call);
    assert!(matches!(result.unwrap(), NvIndexState::Available));
    assert_eq!(provisioned_ak_cert_after_call, provisioned_ak_cert);

    // Test updating the provisioned nv index (with ownerwrite permission)
    // Write a very short AKCert that will definitely fit in the already-provisioned space.
    let ak_cert_input = [7u8; 10];
    let result =
        tpm_engine_helper.nv_write(TPM20_RH_OWNER, None, TPM_NV_INDEX_AIK_CERT, &ak_cert_input);
    assert!(result.is_ok());

    // Ensure the data is overwritten
    let mut ak_cert_output = [0u8; TPM_DEFAULT_AKCERT_SIZE];
    let result = tpm_engine_helper.read_from_nv_index(TPM_NV_INDEX_AIK_CERT, &mut ak_cert_output);
    assert!(matches!(result.unwrap(), NvIndexState::Available));

    assert_ne!(&ak_cert_output, &provisioned_ak_cert);

    // Ensure that write_to_nv_index fails because the nv index is not platform-defined
    let ak_cert_input = [8u8; 10];
    let result =
        tpm_engine_helper.write_to_nv_index(AUTH_VALUE, TPM_NV_INDEX_AIK_CERT, &ak_cert_input);
    assert!(result.is_err());
    assert!(matches!(
        result.unwrap_err(),
        Error::InvalidPermission {
            platform_created: false,
            ..
        }
    ));
}

#[test]
fn test_initialize_guest_secret_key() {
    const GUEST_SECRET_KEY_BLOB: [u8; 422] = [
        0x01, 0x16, 0x00, 0x01, 0x00, 0x0b, 0x00, 0x02, 0x00, 0x40, 0x00, 0x00, 0x00, 0x10, 0x00,
        0x10, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x01, 0x00, 0xec, 0x0d, 0xdf, 0xf3, 0xa2, 0x0f,
        0xd4, 0x66, 0xe8, 0x53, 0x8a, 0x1c, 0x54, 0x00, 0x69, 0xbe, 0x57, 0xc4, 0x9a, 0x7d, 0x4d,
        0xd2, 0xbc, 0xd7, 0x6b, 0x93, 0xe4, 0x15, 0x3f, 0x2f, 0xbb, 0x77, 0xf7, 0x1b, 0x19, 0x88,
        0x04, 0xc7, 0x42, 0xda, 0xa2, 0x00, 0xc7, 0x8c, 0x2a, 0xfc, 0x48, 0xa5, 0xe7, 0x3f, 0x4e,
        0x06, 0x33, 0xa8, 0xb1, 0xcf, 0x09, 0x8c, 0xfe, 0x3f, 0x91, 0x43, 0xa9, 0x4a, 0x8e, 0x05,
        0xe7, 0xf0, 0x57, 0x68, 0xb5, 0x68, 0xe7, 0x7d, 0xb3, 0x5c, 0xd5, 0x6c, 0xb9, 0x48, 0x5e,
        0x0f, 0xf9, 0x0f, 0xe9, 0xf9, 0x42, 0x57, 0x08, 0x8c, 0xff, 0x3f, 0x67, 0xd1, 0x9b, 0xb6,
        0xa7, 0x7d, 0xa6, 0xa9, 0xcb, 0x00, 0x4b, 0x1d, 0xa6, 0xf3, 0x09, 0xe0, 0x87, 0x12, 0xc6,
        0x8b, 0xbe, 0x61, 0xaf, 0xc6, 0x30, 0x35, 0xcc, 0x10, 0x68, 0x8b, 0x76, 0x36, 0x16, 0xcb,
        0xce, 0x83, 0x6c, 0x7e, 0x9e, 0x1e, 0x08, 0xc7, 0x20, 0x7d, 0x1d, 0xd4, 0xc4, 0x4f, 0x3a,
        0x34, 0x06, 0xe9, 0xae, 0xf5, 0x50, 0xd9, 0x5d, 0xb2, 0x30, 0x74, 0xed, 0x38, 0x74, 0x31,
        0x3e, 0x1d, 0xfd, 0x15, 0x26, 0x8f, 0x48, 0x5b, 0x22, 0x2f, 0xa0, 0xc3, 0xd0, 0x1c, 0x56,
        0x4f, 0xb1, 0x39, 0xe7, 0x93, 0xc1, 0x3d, 0x2d, 0x42, 0x57, 0x33, 0x4d, 0xdc, 0x90, 0x41,
        0x83, 0x6a, 0x21, 0x15, 0xbd, 0x2c, 0x5c, 0xa1, 0xc1, 0xda, 0xf9, 0x4c, 0x15, 0x89, 0x41,
        0x84, 0xad, 0xb9, 0xfc, 0xc7, 0x81, 0xa3, 0x93, 0xe9, 0xd8, 0xfc, 0xe3, 0x3f, 0x4d, 0x6f,
        0x71, 0x14, 0x9e, 0xe2, 0xe2, 0xfa, 0xa1, 0x8d, 0x3a, 0x80, 0xea, 0x5a, 0xc9, 0x0f, 0x23,
        0xb9, 0x3e, 0x36, 0xbb, 0xff, 0x4e, 0x9c, 0x40, 0x6f, 0x1d, 0x75, 0x39, 0x96, 0x9b, 0xac,
        0x54, 0xe1, 0x0b, 0x4b, 0x08, 0x3e, 0xd5, 0x94, 0x7d, 0xad, 0x00, 0x8a, 0x00, 0x88, 0x00,
        0x01, 0x00, 0x00, 0x00, 0x00, 0x00, 0x80, 0xf7, 0xca, 0x88, 0xe3, 0x6a, 0x67, 0xbd, 0xb7,
        0xfe, 0xc9, 0x49, 0x35, 0x84, 0x23, 0xf3, 0x26, 0x7f, 0xaa, 0xf6, 0xee, 0x14, 0x86, 0x55,
        0xbf, 0x26, 0xd3, 0x21, 0x9f, 0x8a, 0xb2, 0x1f, 0x2e, 0x79, 0x69, 0x7b, 0xa0, 0xad, 0x06,
        0x2e, 0x13, 0xda, 0x8a, 0x5c, 0x59, 0x98, 0x75, 0xf5, 0xfa, 0x2e, 0x14, 0xe6, 0xef, 0xc2,
        0x3c, 0xa6, 0x11, 0x90, 0xf8, 0xc3, 0x6f, 0x7d, 0xc5, 0x4c, 0x5c, 0xe8, 0x6a, 0x7f, 0x24,
        0xa0, 0xef, 0x70, 0x5e, 0xc8, 0x92, 0xa2, 0x3c, 0xa8, 0xa4, 0x0b, 0x38, 0xb1, 0xd5, 0xeb,
        0x67, 0x8f, 0x76, 0x65, 0x73, 0xd5, 0x6b, 0xb1, 0xad, 0x85, 0xb0, 0x0b, 0x0e, 0x41, 0x6b,
        0xba, 0x1c, 0x2a, 0x02, 0x11, 0xb7, 0xb4, 0x72, 0x74, 0xe2, 0x9f, 0x8e, 0x42, 0xa1, 0x38,
        0x24, 0x25, 0xc8, 0xcf, 0x53, 0x27, 0x1b, 0x4e, 0xcc, 0x8c, 0x0b, 0x4b, 0x69, 0x3f, 0x7b,
        0x00, 0x00,
    ];

    const GUEST_SECRET_KEY_PUBLIC: [u8; 256] = [
        0xec, 0x0d, 0xdf, 0xf3, 0xa2, 0x0f, 0xd4, 0x66, 0xe8, 0x53, 0x8a, 0x1c, 0x54, 0x00, 0x69,
        0xbe, 0x57, 0xc4, 0x9a, 0x7d, 0x4d, 0xd2, 0xbc, 0xd7, 0x6b, 0x93, 0xe4, 0x15, 0x3f, 0x2f,
        0xbb, 0x77, 0xf7, 0x1b, 0x19, 0x88, 0x04, 0xc7, 0x42, 0xda, 0xa2, 0x00, 0xc7, 0x8c, 0x2a,
        0xfc, 0x48, 0xa5, 0xe7, 0x3f, 0x4e, 0x06, 0x33, 0xa8, 0xb1, 0xcf, 0x09, 0x8c, 0xfe, 0x3f,
        0x91, 0x43, 0xa9, 0x4a, 0x8e, 0x05, 0xe7, 0xf0, 0x57, 0x68, 0xb5, 0x68, 0xe7, 0x7d, 0xb3,
        0x5c, 0xd5, 0x6c, 0xb9, 0x48, 0x5e, 0x0f, 0xf9, 0x0f, 0xe9, 0xf9, 0x42, 0x57, 0x08, 0x8c,
        0xff, 0x3f, 0x67, 0xd1, 0x9b, 0xb6, 0xa7, 0x7d, 0xa6, 0xa9, 0xcb, 0x00, 0x4b, 0x1d, 0xa6,
        0xf3, 0x09, 0xe0, 0x87, 0x12, 0xc6, 0x8b, 0xbe, 0x61, 0xaf, 0xc6, 0x30, 0x35, 0xcc, 0x10,
        0x68, 0x8b, 0x76, 0x36, 0x16, 0xcb, 0xce, 0x83, 0x6c, 0x7e, 0x9e, 0x1e, 0x08, 0xc7, 0x20,
        0x7d, 0x1d, 0xd4, 0xc4, 0x4f, 0x3a, 0x34, 0x06, 0xe9, 0xae, 0xf5, 0x50, 0xd9, 0x5d, 0xb2,
        0x30, 0x74, 0xed, 0x38, 0x74, 0x31, 0x3e, 0x1d, 0xfd, 0x15, 0x26, 0x8f, 0x48, 0x5b, 0x22,
        0x2f, 0xa0, 0xc3, 0xd0, 0x1c, 0x56, 0x4f, 0xb1, 0x39, 0xe7, 0x93, 0xc1, 0x3d, 0x2d, 0x42,
        0x57, 0x33, 0x4d, 0xdc, 0x90, 0x41, 0x83, 0x6a, 0x21, 0x15, 0xbd, 0x2c, 0x5c, 0xa1, 0xc1,
        0xda, 0xf9, 0x4c, 0x15, 0x89, 0x41, 0x84, 0xad, 0xb9, 0xfc, 0xc7, 0x81, 0xa3, 0x93, 0xe9,
        0xd8, 0xfc, 0xe3, 0x3f, 0x4d, 0x6f, 0x71, 0x14, 0x9e, 0xe2, 0xe2, 0xfa, 0xa1, 0x8d, 0x3a,
        0x80, 0xea, 0x5a, 0xc9, 0x0f, 0x23, 0xb9, 0x3e, 0x36, 0xbb, 0xff, 0x4e, 0x9c, 0x40, 0x6f,
        0x1d, 0x75, 0x39, 0x96, 0x9b, 0xac, 0x54, 0xe1, 0x0b, 0x4b, 0x08, 0x3e, 0xd5, 0x94, 0x7d,
        0xad,
    ];

    let mut tpm_engine_helper = create_tpm_engine_helper();
    initialize_pre_provisioned_tpm(&mut tpm_engine_helper);

    // Ensure SRK is provisioned
    assert!(
        tpm_engine_helper
            .find_object(TPM_RSA_SRK_HANDLE)
            .unwrap()
            .is_some()
    );

    // Ensure guest secret key is not initialized yet
    assert!(
        tpm_engine_helper
            .find_object(TPM_GUEST_SECRET_HANDLE)
            .unwrap()
            .is_none()
    );

    // Negative test: invalid data blob
    let result = tpm_engine_helper.initialize_guest_secret_key(&[]);
    assert!(result.is_err());
    let err = result.unwrap_err();
    assert!(matches!(err, Error::DeserializeGuestSecretKey));

    // Positive test

    // Apply zero paddings to `GUEST_SECRET_KEY_MAX_SIZE`
    let data_with_zero_paddings = {
        let mut data = GUEST_SECRET_KEY_BLOB.to_vec();
        data.resize(2048, 0);

        data
    };

    let result = tpm_engine_helper.initialize_guest_secret_key(&data_with_zero_paddings);
    assert!(result.is_ok());

    // Ensure guest secret key is initialized
    let result = tpm_engine_helper.find_object(TPM_GUEST_SECRET_HANDLE);
    assert!(result.is_ok());
    let result = result.unwrap();
    assert!(result.is_some());

    let read_public_reply = result.unwrap();
    let unique = read_public_reply.out_public.public_area.unique.serialize();
    let offset = size_of_val(&read_public_reply.out_public.public_area.unique.size);
    assert_eq!(
        &unique[offset..offset + RSA_2K_MODULUS_SIZE],
        GUEST_SECRET_KEY_PUBLIC
    );

    // Negative test: Test without SRK

    restart_tpm_engine(&mut tpm_engine_helper, true, true);

    // Ensure SRK is not provisioned
    assert!(
        tpm_engine_helper
            .find_object(TPM_RSA_SRK_HANDLE)
            .unwrap()
            .is_none()
    );

    // Ensure guest secret key is not initialized yet
    assert!(
        tpm_engine_helper
            .find_object(TPM_GUEST_SECRET_HANDLE)
            .unwrap()
            .is_none()
    );

    // Expect to fail due to SRK not found
    let result = tpm_engine_helper.initialize_guest_secret_key(&GUEST_SECRET_KEY_BLOB);
    assert!(result.is_err());
    if let Error::SrkNotFound(srk_handle) = result.unwrap_err() {
        assert_eq!(srk_handle, TPM_RSA_SRK_HANDLE);
    } else {
        panic!()
    }
}

#[test]
fn test_startup_and_self_test() {
    let mut tpm_engine_helper = create_tpm_engine_helper();
    restart_tpm_engine(&mut tpm_engine_helper, false, false);

    // Negative test for SelfTest (expect to fail before StartUp is called)
    let result = tpm_engine_helper.self_test(true);
    assert!(result.is_err());
    let err = result.unwrap_err();
    if let TpmCommandError::TpmCommandFailed { response_code } = err {
        assert_ne!(response_code, ResponseCode::Success as u32);
    } else {
        panic!()
    }

    // Positive tests
    let result = tpm_engine_helper.startup(StartupType::Clear);
    assert!(result.is_ok());

    let result = tpm_engine_helper.self_test(true);
    assert!(result.is_ok());

    // Negative test for StartUp
    let result = tpm_engine_helper.startup(StartupType::Clear);
    assert!(result.is_err());
    let err = result.unwrap_err();
    if let TpmCommandError::TpmCommandFailed { response_code } = err {
        assert_ne!(response_code, ResponseCode::Success as u32);
    } else {
        panic!()
    }
}

#[test]
fn test_change_seed() {
    let mut tpm_engine_helper = create_tpm_engine_helper();
    restart_tpm_engine(&mut tpm_engine_helper, false, true);

    // Positive test
    let auth_handle = TPM20_RH_PLATFORM;
    let result = tpm_engine_helper.change_seed(auth_handle, CommandCodeEnum::ChangeEPS);
    assert!(result.is_ok());

    let result = tpm_engine_helper.change_seed(auth_handle, CommandCodeEnum::ChangePPS);
    assert!(result.is_ok());

    // Negative test
    let invalid_auth_handle = ReservedHandle(0.into());
    let result = tpm_engine_helper.change_seed(invalid_auth_handle, CommandCodeEnum::ChangeEPS);
    assert!(result.is_err());
    let err = result.unwrap_err();
    if let TpmCommandError::TpmCommandFailed { response_code } = err {
        assert_ne!(response_code, ResponseCode::Success as u32);
    } else {
        panic!()
    }

    let invalid_auth_handle = ReservedHandle(0.into());
    let result = tpm_engine_helper.change_seed(invalid_auth_handle, CommandCodeEnum::ChangePPS);
    assert!(result.is_err());
    let err = result.unwrap_err();
    if let TpmCommandError::TpmCommandFailed { response_code } = err {
        assert_ne!(response_code, ResponseCode::Success as u32);
    } else {
        panic!()
    }
}

#[test]
fn test_pcr_allocate() {
    let mut tpm_engine_helper = create_tpm_engine_helper();
    restart_tpm_engine(&mut tpm_engine_helper, false, true);

    // Positive test
    let auth_handle = TPM20_RH_PLATFORM;
    let result = tpm_engine_helper.pcr_allocate(auth_handle, 0b000011, 0b00001);
    assert!(result.is_ok());
    let response_code = result.unwrap();
    assert_eq!(response_code, ResponseCode::Success as u32);

    // Negative test
    let invalid_auth_handle = ReservedHandle(0.into());
    let result = tpm_engine_helper.pcr_allocate(invalid_auth_handle, 0, 0);
    assert!(result.is_err());
    let err = result.unwrap_err();
    if let TpmCommandError::TpmCommandFailed { response_code } = err {
        assert_ne!(response_code, ResponseCode::Success as u32);
    } else {
        panic!()
    }
}

#[test]
fn test_create_primary() {
    let mut tpm_engine_helper = create_tpm_engine_helper();
    restart_tpm_engine(&mut tpm_engine_helper, false, true);

    // Positive tests

    // Create EK
    let result = ek_pub_template();
    assert!(result.is_ok());
    let ek_pub_template = result.unwrap();

    let auth_handle = TPM20_RH_ENDORSEMENT;
    let result = tpm_engine_helper.create_primary(auth_handle, ek_pub_template);
    assert!(result.is_ok());
    let response = result.unwrap();
    assert_ne!(response.out_public.size.get(), 0);

    // Create AK
    let result = ak_pub_template();
    assert!(result.is_ok());
    let ak_pub_template = result.unwrap();

    let auth_handle = TPM20_RH_ENDORSEMENT;
    let result = tpm_engine_helper.create_primary(auth_handle, ak_pub_template);
    assert!(result.is_ok());
    let response = result.unwrap();
    assert_ne!(response.out_public.size.get(), 0);

    // Negative test
    let invalid_auth_handle = ReservedHandle(0.into());
    let template = TpmtPublic::new_zeroed();
    let result = tpm_engine_helper.create_primary(invalid_auth_handle, template);
    assert!(result.is_err());
    let err = result.unwrap_err();
    if let TpmCommandError::TpmCommandFailed { response_code } = err {
        assert_ne!(response_code, ResponseCode::Success as u32);
    } else {
        panic!()
    }
}

#[test]
fn test_evict_control() {
    let ak_handle = TPM_AZURE_AIK_HANDLE;

    let mut tpm_engine_helper = create_tpm_engine_helper();
    restart_tpm_engine(&mut tpm_engine_helper, false, true);

    // Create AK
    let result = ak_pub_template();
    assert!(result.is_ok());
    let ak_pub_template = result.unwrap();

    let auth_handle = TPM20_RH_ENDORSEMENT;
    let result = tpm_engine_helper.create_primary(auth_handle, ak_pub_template);
    assert!(result.is_ok());
    let response = result.unwrap();
    assert_ne!(response.out_public.size.get(), 0);
    let ak_object_handle = response.object_handle;

    // Positive test
    let auth_handle = TPM20_RH_OWNER;
    let result = tpm_engine_helper.evict_control(auth_handle, ak_object_handle, ak_handle);
    assert!(result.is_ok());

    // Negative test
    let invalid_auth_handle = ReservedHandle(0.into());
    let result = tpm_engine_helper.evict_control(invalid_auth_handle, ak_object_handle, ak_handle);
    assert!(result.is_err());
    let err = result.unwrap_err();
    if let TpmCommandError::TpmCommandFailed { response_code } = err {
        assert_ne!(response_code, ResponseCode::Success as u32);
    } else {
        panic!()
    }
}

#[test]
fn test_flush_context() {
    let mut tpm_engine_helper = create_tpm_engine_helper();
    restart_tpm_engine(&mut tpm_engine_helper, false, true);

    // Create AK
    let result = ak_pub_template();
    assert!(result.is_ok());
    let ak_pub_template = result.unwrap();

    let auth_handle = TPM20_RH_ENDORSEMENT;
    let result = tpm_engine_helper.create_primary(auth_handle, ak_pub_template);
    assert!(result.is_ok());
    let response = result.unwrap();
    assert_ne!(response.out_public.size.get(), 0);
    let ak_object_handle = response.object_handle;

    // Positive test
    let result = tpm_engine_helper.flush_context(ak_object_handle);
    assert!(result.is_ok());

    // Negative test
    let invalid_handle = ReservedHandle(0.into());
    let result = tpm_engine_helper.flush_context(invalid_handle);
    assert!(result.is_err());
    let err = result.unwrap_err();
    if let TpmCommandError::TpmCommandFailed { response_code } = err {
        assert_ne!(response_code, ResponseCode::Success as u32);
    } else {
        panic!()
    }
}

#[test]
fn test_read_public() {
    let ak_handle = TPM_AZURE_AIK_HANDLE;

    let mut tpm_engine_helper = create_tpm_engine_helper();
    restart_tpm_engine(&mut tpm_engine_helper, false, true);

    // Create AK
    let result = ak_pub_template();
    assert!(result.is_ok());
    let ak_pub_template = result.unwrap();

    let auth_handle = TPM20_RH_ENDORSEMENT;
    let result = tpm_engine_helper.create_primary(auth_handle, ak_pub_template);
    assert!(result.is_ok());
    let response = result.unwrap();
    assert_ne!(response.out_public.size.get(), 0);
    let ak_object_handle = response.object_handle;

    let auth_handle = TPM20_RH_OWNER;
    let result = tpm_engine_helper.evict_control(auth_handle, ak_object_handle, ak_handle);
    assert!(result.is_ok());

    // Positive test
    let result = tpm_engine_helper.read_public(ak_handle);
    assert!(result.is_ok());

    // Negative test
    let invalid_object_handle = ReservedHandle((ak_handle.0.get() + 10).into()); // pick an unallocated handle
    let result = tpm_engine_helper.read_public(invalid_object_handle);
    assert!(result.is_err());
    let err = result.unwrap_err();
    if let TpmCommandError::TpmCommandFailed { response_code } = err {
        assert_eq!(
            response_code,
            (ResponseCode::Handle as u32 | ResponseCode::Rc1 as u32)
        );
    } else {
        panic!()
    }
}

#[test]
fn test_nv_define_space() {
    let nv_index = TPM_NV_INDEX_AIK_CERT;
    let nv_index_size = test_tpm::MAX_NV_INDEX_SIZE;

    let mut tpm_engine_helper = create_tpm_engine_helper();
    restart_tpm_engine(&mut tpm_engine_helper, false, true);

    // Positive test
    let auth_handle = TPM20_RH_PLATFORM;
    let result =
        tpm_engine_helper.nv_define_space(auth_handle, AUTH_VALUE, nv_index, nv_index_size);
    assert!(result.is_ok());

    // Negative test
    let invalid_auth_handle = ReservedHandle(0.into());
    let result =
        tpm_engine_helper.nv_define_space(invalid_auth_handle, AUTH_VALUE, nv_index, nv_index_size);
    assert!(result.is_err());
    let err = result.unwrap_err();
    if let TpmCommandError::TpmCommandFailed { response_code } = err {
        assert_ne!(response_code, ResponseCode::Success as u32);
    } else {
        panic!()
    }
}

#[test]
fn test_nv_read_public() {
    let nv_index = TPM_NV_INDEX_AIK_CERT;
    let nv_index_size = test_tpm::MAX_NV_INDEX_SIZE;

    let mut tpm_engine_helper = create_tpm_engine_helper();
    restart_tpm_engine(&mut tpm_engine_helper, false, true);

    let auth_handle = TPM20_RH_PLATFORM;
    let result =
        tpm_engine_helper.nv_define_space(auth_handle, AUTH_VALUE, nv_index, nv_index_size);
    assert!(result.is_ok());

    // Positive test
    let result = tpm_engine_helper.nv_read_public(nv_index);
    assert!(result.is_ok());
    let response = result.unwrap();

    // Check the flags set by `nv_define_space`
    let nv_bits = TpmaNvBits::from(response.nv_public.nv_public.attributes.0.get());
    assert!(nv_bits.nv_authread());
    assert!(nv_bits.nv_authwrite());
    assert!(nv_bits.nv_ownerread());
    assert!(nv_bits.nv_platformcreate());
    assert!(nv_bits.nv_no_da());

    // Negative test
    let invalid_nv_index = nv_index + 10; // Pick an undefined index
    let result = tpm_engine_helper.nv_read_public(invalid_nv_index);
    assert!(result.is_err());
    let err = result.unwrap_err();
    if let TpmCommandError::TpmCommandFailed { response_code } = err {
        assert_eq!(
            response_code,
            (ResponseCode::Handle as u32 | ResponseCode::Rc1 as u32)
        );
    } else {
        panic!()
    }
}

#[test]
fn test_nv_read_write() {
    let nv_index = TPM_NV_INDEX_AIK_CERT;
    let nv_index_size = test_tpm::MAX_NV_INDEX_SIZE;

    let mut tpm_engine_helper = create_tpm_engine_helper();
    restart_tpm_engine(&mut tpm_engine_helper, false, true);

    let auth_handle = TPM20_RH_PLATFORM;
    let result =
        tpm_engine_helper.nv_define_space(auth_handle, AUTH_VALUE, nv_index, nv_index_size);
    assert!(result.is_ok());

    // Positive tests

    // Write with data size equal to nv_index_size
    let input_data = vec![7u8; nv_index_size.into()];
    let result = tpm_engine_helper.nv_write(
        ReservedHandle(nv_index.into()),
        Some(AUTH_VALUE),
        nv_index,
        input_data.as_ref(),
    );
    assert!(result.is_ok());

    // Read the data
    let mut output_data = vec![0u8; nv_index_size.into()];
    let result = tpm_engine_helper.nv_read(
        TPM20_RH_OWNER,
        nv_index,
        nv_index_size,
        output_data.as_mut(),
    );
    assert!(result.is_ok());
    assert_eq!(input_data, output_data);

    // Write with data size smaller to nv_index_size
    let data_size = 512;
    assert!(data_size < nv_index_size.into());
    let input_data = vec![6u8; data_size];
    let result = tpm_engine_helper.nv_write(
        ReservedHandle(nv_index.into()),
        Some(AUTH_VALUE),
        nv_index,
        input_data.as_ref(),
    );
    assert!(result.is_ok());

    // Read the data
    let mut output_data = vec![0u8; nv_index_size.into()];
    let result = tpm_engine_helper.nv_read(
        TPM20_RH_OWNER,
        nv_index,
        nv_index_size,
        output_data.as_mut(),
    );
    assert!(result.is_ok());
    assert_eq!(input_data, output_data[..data_size]);

    // Negative tests

    // test nv_write with invalid auth handle
    let invalid_auth_handle = ReservedHandle(0.into());
    let input_data = vec![7u8; nv_index_size.into()];
    let result = tpm_engine_helper.nv_write(
        invalid_auth_handle,
        Some(AUTH_VALUE),
        nv_index,
        input_data.as_ref(),
    );
    assert!(result.is_err());
    let err = result.unwrap_err();
    if let TpmCommandError::TpmCommandFailed { response_code } = err {
        assert_ne!(response_code, ResponseCode::Success as u32);
    } else {
        panic!()
    }

    // test nv_read with invalid auth handle
    let invalid_auth_handle = ReservedHandle(0.into());
    let mut output_data = vec![0u8; nv_index_size.into()];
    let result = tpm_engine_helper.nv_read(
        invalid_auth_handle,
        nv_index,
        nv_index_size,
        output_data.as_mut(),
    );
    assert!(result.is_err());
    let err = result.unwrap_err();
    if let TpmCommandError::TpmCommandFailed { response_code } = err {
        assert_ne!(response_code, ResponseCode::Success as u32);
    } else {
        panic!()
    }
}

#[test]
fn test_nv_undefine_space() {
    let nv_index = TPM_NV_INDEX_AIK_CERT;
    let nv_index_size = test_tpm::MAX_NV_INDEX_SIZE;

    let mut tpm_engine_helper = create_tpm_engine_helper();
    restart_tpm_engine(&mut tpm_engine_helper, false, true);

    let auth_handle = TPM20_RH_PLATFORM;
    let result =
        tpm_engine_helper.nv_define_space(auth_handle, AUTH_VALUE, nv_index, nv_index_size);

    assert!(result.is_ok());
    // Positive test
    let auth_handle = TPM20_RH_PLATFORM;
    let result = tpm_engine_helper.nv_undefine_space(auth_handle, nv_index);
    assert!(result.is_ok());

    // Negative test
    let invalid_auth_handle = ReservedHandle(0.into());
    let result = tpm_engine_helper.nv_undefine_space(invalid_auth_handle, nv_index);
    assert!(result.is_err());
    let err = result.unwrap_err();
    if let TpmCommandError::TpmCommandFailed { response_code } = err {
        assert_ne!(response_code, ResponseCode::Success as u32);
    } else {
        panic!()
    }
}

#[test]
fn test_clear_control() {
    let mut tpm_engine_helper = create_tpm_engine_helper();
    restart_tpm_engine(&mut tpm_engine_helper, false, true);

    // Positive test
    let auth_handle = TPM20_RH_PLATFORM;
    let result = tpm_engine_helper.clear_control(auth_handle, false);
    assert!(result.is_ok());

    // Negative test
    let invalid_auth_handle = ReservedHandle(0.into());
    let result = tpm_engine_helper.clear_control(invalid_auth_handle, false);
    assert!(result.is_err());
    let err = result.unwrap_err();
    if let TpmCommandError::TpmCommandFailed { response_code } = err {
        assert_ne!(response_code, ResponseCode::Success as u32);
    } else {
        panic!()
    }
}

#[test]
fn test_clear() {
    let mut tpm_engine_helper = create_tpm_engine_helper();
    restart_tpm_engine(&mut tpm_engine_helper, false, true);

    // Positive test

    // Enable the clear command
    let result = tpm_engine_helper.clear_tpm_platform_context();
    assert!(result.is_ok());
    let response_code = result.unwrap();
    assert_eq!(response_code, ResponseCode::Success as u32);

    // Negative test

    // Disable the clear command
    let auth_handle = TPM20_RH_PLATFORM;
    let result = tpm_engine_helper.clear_control(auth_handle, true);
    assert!(result.is_ok());

    let result = tpm_engine_helper.clear(auth_handle);
    assert!(result.is_err());
    let err = result.unwrap_err();
    if let TpmCommandError::TpmCommandFailed { response_code } = err {
        assert_ne!(response_code, ResponseCode::Success as u32);
    } else {
        panic!()
    }
}
struct TpmtSensitive {
    /// TPMI_ALG_PUBLIC
    sensitive_type: AlgId,
    /// `TPM2B_AUTH`
    auth_value: Tpm2bBuffer,
    /// `TPM2B_DIGEST`
    seed_value: Tpm2bBuffer,
    /// `TPM2B_PRIVATE_KEY_RSA`
    sensitive: Tpm2bBuffer,
}

impl TpmtSensitive {
    fn serialize(&self) -> Vec<u8> {
        let mut buffer = Vec::new();

        buffer.extend_from_slice(self.sensitive_type.as_bytes());
        buffer.extend_from_slice(&self.auth_value.serialize());
        buffer.extend_from_slice(&self.seed_value.serialize());
        buffer.extend_from_slice(&self.sensitive.serialize());

        buffer
    }
}

fn generate_rsa() -> (TpmtPublic, Tpm2bBuffer) {
    // Using hard-coded value to avoid OpenSSL dependency
    // RSA-2k public modulus
    const N: [u8; 256] = [
        0xbc, 0x85, 0x76, 0x9b, 0x24, 0xf5, 0x55, 0x2b, 0x58, 0x77, 0xf5, 0xbd, 0x3d, 0x15, 0x2f,
        0xa4, 0x5b, 0xda, 0x17, 0x74, 0xd7, 0x97, 0x64, 0xd5, 0x64, 0x0a, 0x51, 0xb0, 0x54, 0x98,
        0xac, 0x8c, 0xf7, 0xb3, 0xf2, 0x45, 0x32, 0xf9, 0x99, 0xd2, 0x9e, 0xb4, 0xf3, 0x49, 0xb7,
        0xf2, 0x27, 0xe3, 0xe4, 0x5d, 0xa6, 0xe2, 0xc2, 0x0f, 0x58, 0x02, 0x65, 0xf7, 0x8e, 0xe7,
        0xd0, 0x41, 0x8a, 0xd4, 0xa2, 0x71, 0x7d, 0x0f, 0x27, 0x51, 0x94, 0x9b, 0x5d, 0xd3, 0x0e,
        0x05, 0xe0, 0xae, 0x2e, 0x2f, 0x3c, 0xfd, 0x46, 0x28, 0x0a, 0x70, 0x59, 0x74, 0x5a, 0xd7,
        0xac, 0x54, 0x92, 0x89, 0xb2, 0xec, 0xb8, 0x38, 0xdf, 0x4d, 0xdb, 0x54, 0xa7, 0x9f, 0x00,
        0xba, 0x9b, 0x8d, 0x2e, 0xee, 0x60, 0xd3, 0x47, 0xea, 0x70, 0x53, 0xb9, 0x26, 0x7b, 0x1f,
        0x82, 0x33, 0x22, 0x65, 0x7a, 0x60, 0xe0, 0xba, 0xdf, 0x60, 0x55, 0xcc, 0xc2, 0x07, 0x16,
        0x7f, 0x6c, 0x07, 0xf0, 0xf8, 0xf5, 0xa6, 0xba, 0xea, 0xc0, 0x6d, 0x45, 0x38, 0x8d, 0xca,
        0x0d, 0xa6, 0x98, 0x21, 0xba, 0xdd, 0x27, 0x0f, 0x8d, 0x7e, 0x7c, 0x7a, 0xee, 0x44, 0xc7,
        0xa7, 0xd4, 0x3d, 0x39, 0x70, 0x4d, 0xde, 0xb1, 0x72, 0x56, 0x6e, 0xe9, 0x50, 0x69, 0x46,
        0x56, 0xd9, 0x83, 0x89, 0x8e, 0xe6, 0xf7, 0x7b, 0xce, 0xf0, 0x75, 0x8e, 0x18, 0xea, 0x22,
        0xc5, 0x62, 0xa7, 0x6b, 0x59, 0x80, 0xe8, 0x68, 0xb2, 0x57, 0xdc, 0xfe, 0xd1, 0xe0, 0xda,
        0xeb, 0x0f, 0x12, 0x64, 0xb2, 0x7a, 0x1f, 0x1a, 0x97, 0xa9, 0xb6, 0xdd, 0xd7, 0x78, 0x82,
        0x90, 0x07, 0xa1, 0x9d, 0x00, 0xff, 0xa9, 0x52, 0xe3, 0x0a, 0xa8, 0xa5, 0x2f, 0xcd, 0xdf,
        0x79, 0xec, 0x35, 0xb4, 0x81, 0xad, 0xa9, 0x45, 0x50, 0x30, 0x58, 0x0b, 0xed, 0xdf, 0x10,
        0x69,
    ];
    // RSA-2k private prime
    const P: [u8; 128] = [
        0xe8, 0x66, 0x31, 0x98, 0xe7, 0xab, 0xd7, 0xbe, 0x1f, 0xa9, 0x13, 0xe2, 0xd0, 0x4d, 0xd0,
        0x0a, 0xb0, 0xd1, 0x39, 0xc0, 0xc3, 0x6f, 0x4b, 0xdc, 0x4d, 0xe2, 0x03, 0xf9, 0xd4, 0xd9,
        0xb5, 0x47, 0x94, 0x97, 0x5b, 0x51, 0xe3, 0x1a, 0x25, 0x7f, 0x14, 0x50, 0xe8, 0x12, 0x21,
        0xd0, 0x0e, 0x51, 0x9a, 0xc3, 0xc5, 0x05, 0x55, 0xe8, 0x31, 0xb8, 0x44, 0xbd, 0x71, 0xa6,
        0x5b, 0x88, 0x05, 0x7b, 0x75, 0xd9, 0x75, 0xba, 0x43, 0x55, 0x6a, 0x72, 0x15, 0x0e, 0xd4,
        0x09, 0xab, 0x69, 0xee, 0xac, 0x3b, 0x68, 0x13, 0x54, 0x43, 0x63, 0x73, 0xb7, 0x7b, 0x5d,
        0x2c, 0x01, 0xb4, 0x1e, 0xfc, 0x88, 0xfe, 0xa6, 0x04, 0x27, 0xba, 0x17, 0x0a, 0x7e, 0xc3,
        0xa8, 0xea, 0xb9, 0x37, 0x6d, 0x81, 0x91, 0x6a, 0x70, 0xfa, 0x4f, 0x18, 0xfb, 0xcf, 0x7b,
        0x45, 0x12, 0xd7, 0x50, 0x64, 0xd6, 0xc8, 0x73,
    ];

    let symmetric = TpmtSymDefObject::new(AlgIdEnum::NULL.into(), None, None);
    let scheme = TpmtRsaScheme::new(AlgIdEnum::RSASSA.into(), Some(AlgIdEnum::SHA256.into()));
    let rsa_params = TpmsRsaParams::new(symmetric, scheme, RSA_2K_MODULUS_BITS, 0);

    let object_attributes = TpmaObjectBits::new()
        .with_user_with_auth(true)
        .with_sign_encrypt(true);

    let unique = {
        let mut data = [0u8; RSA_2K_MODULUS_SIZE];
        data.copy_from_slice(&N);

        data
    };

    let result = TpmtPublic::new(
        AlgIdEnum::RSA.into(),
        AlgIdEnum::SHA256.into(),
        object_attributes,
        &[],
        rsa_params,
        &unique,
    );
    assert!(result.is_ok());

    let rsa_public = result.unwrap();

    let result = Tpm2bBuffer::new(&P);
    assert!(result.is_ok());
    let sensitive = result.unwrap();

    let rsa_sensitive = TpmtSensitive {
        sensitive_type: AlgIdEnum::RSA.into(),
        auth_value: Tpm2bBuffer::new_zeroed(),
        seed_value: Tpm2bBuffer::new_zeroed(),
        sensitive,
    };

    let result = Tpm2bBuffer::new(&rsa_sensitive.serialize());
    assert!(result.is_ok());
    let rsa_private = result.unwrap();

    (rsa_public, rsa_private)
}

fn rsa_srk_template() -> Result<TpmtPublic, TpmHelperUtilityError> {
    let symmetric = TpmtSymDefObject::new(
        AlgIdEnum::AES.into(),
        Some(128),
        Some(AlgIdEnum::CFB.into()),
    );
    let scheme = TpmtRsaScheme::new(AlgIdEnum::NULL.into(), None);
    let rsa_params = TpmsRsaParams::new(symmetric, scheme, RSA_2K_MODULUS_BITS, 0);

    let object_attributes = TpmaObjectBits::new()
        .with_fixed_tpm(true)
        .with_fixed_parent(true)
        .with_sensitive_data_origin(true)
        .with_user_with_auth(true)
        .with_no_da(true)
        .with_restricted(true)
        .with_decrypt(true);

    let in_public = TpmtPublic::new(
        AlgIdEnum::RSA.into(),
        AlgIdEnum::SHA256.into(),
        object_attributes,
        &[],
        rsa_params,
        &[0u8; RSA_2K_MODULUS_SIZE],
    )
    .map_err(TpmHelperUtilityError::InvalidInputParameter)?;

    Ok(in_public)
}

#[test]
fn test_import_load() {
    let mut tpm_engine_helper = create_tpm_engine_helper();
    restart_tpm_engine(&mut tpm_engine_helper, false, true);

    // Create SRK
    let result = rsa_srk_template();
    assert!(result.is_ok());
    let rsa_srk_template = result.unwrap();

    // Positive tests

    let auth_handle = TPM20_RH_OWNER;
    let result = tpm_engine_helper.create_primary(auth_handle, rsa_srk_template);
    assert!(result.is_ok());
    let create_primary_reply = result.unwrap();
    assert_ne!(create_primary_reply.out_public.size.get(), 0);

    let (rsa_public, rsa_private) = generate_rsa();
    let object_public = Tpm2bPublic::new(rsa_public);
    let result = Tpm2bBuffer::new(&rsa_private.serialize());
    assert!(result.is_ok());
    let duplicate = result.unwrap();
    let in_sym_seed = Tpm2bBuffer::new_zeroed();

    let result = tpm_engine_helper.import(
        create_primary_reply.object_handle,
        &object_public,
        &duplicate,
        &in_sym_seed,
    );
    assert!(result.is_ok());
    let import_reply = result.unwrap();

    let in_public = object_public;
    let in_private = import_reply.out_private;

    let result =
        tpm_engine_helper.load(create_primary_reply.object_handle, &in_private, &in_public);
    assert!(result.is_ok());

    // Negative tests

    let invalid_auth_handle = ReservedHandle(0.into());
    let result = tpm_engine_helper.import(
        invalid_auth_handle,
        &object_public,
        &duplicate,
        &in_sym_seed,
    );
    assert!(result.is_err());
    let err = result.unwrap_err();
    if let TpmCommandError::TpmCommandFailed { response_code } = err {
        assert_ne!(response_code, ResponseCode::Success as u32);
    } else {
        panic!()
    }

    let result = tpm_engine_helper.load(invalid_auth_handle, &in_private, &in_public);
    assert!(result.is_err());
    let err = result.unwrap_err();
    if let TpmCommandError::TpmCommandFailed { response_code } = err {
        assert_ne!(response_code, ResponseCode::Success as u32);
    } else {
        panic!()
    }
}

#[test]
fn test_restore_owner_defined() {
    const AK_CERT_INPUT_512: [u8; 512] = [7u8; 512];

    let mut tpm_engine_helper = create_tpm_engine_helper();
    restart_tpm_engine(&mut tpm_engine_helper, false, true);

    // Test allocating a platform-defined AKCert index and mitigating it back to owner-defined.

    let result = tpm_engine_helper.allocate_guest_attestation_nv_indices(
        AUTH_VALUE,
        AllocateNvIndicesParams {
            preserve_ak_cert: false,
            support_attestation_report: true,
            mitigate_legacy_akcert: false,
            create_if_missing: true,
        },
    );
    assert!(result.is_ok());

    let result = tpm_engine_helper
        .find_nv_index(TPM_NV_INDEX_AIK_CERT)
        .expect("find_nv_index should succeed")
        .expect("AKCert NV index present");
    let nv_bits = TpmaNvBits::from(result.nv_public.nv_public.attributes.0.get());
    assert!(nv_bits.nv_platformcreate());

    let result =
        tpm_engine_helper.write_to_nv_index(AUTH_VALUE, TPM_NV_INDEX_AIK_CERT, &AK_CERT_INPUT_512);
    assert!(result.is_ok());

    let result =
        tpm_engine_helper.nv_define_space(TPM20_RH_PLATFORM, AUTH_VALUE, TPM_NV_INDEX_MITIGATED, 1);
    assert!(result.is_ok());

    // TPM has a platform-defined AKCert index and a mitigation marker. This should restore
    // the owner-defined AKCert index.
    let result = tpm_engine_helper.allocate_guest_attestation_nv_indices(
        AUTH_VALUE,
        AllocateNvIndicesParams {
            preserve_ak_cert: false,
            support_attestation_report: true,
            mitigate_legacy_akcert: true,
            create_if_missing: true,
        },
    );
    assert!(result.is_ok());

    let result = tpm_engine_helper
        .find_nv_index(TPM_NV_INDEX_AIK_CERT)
        .expect("find_nv_index should succeed")
        .expect("AKCert NV index present");
    let nv_bits = TpmaNvBits::from(result.nv_public.nv_public.attributes.0.get());
    assert!(!nv_bits.nv_platformcreate());
}

#[test]
fn test_oversized_platform_ak_cert_index() {
    // The index is re-created at `TPM_DEFAULT_AKCERT_SIZE`, so an existing
    // larger index is only reachable on backends whose maximum exceeds it.
    if (test_tpm::MAX_NV_INDEX_SIZE as usize) <= TPM_DEFAULT_AKCERT_SIZE {
        return;
    }

    let oversized_size = test_tpm::MAX_NV_INDEX_SIZE;

    let mut tpm_engine_helper = create_tpm_engine_helper();
    restart_tpm_engine(&mut tpm_engine_helper, false, true);

    let result = tpm_engine_helper.nv_define_space(
        TPM20_RH_PLATFORM,
        AUTH_VALUE,
        TPM_NV_INDEX_AIK_CERT,
        oversized_size,
    );
    assert!(result.is_ok(), "{result:?}");

    let ak_cert_input = vec![7u8; oversized_size as usize];
    let result =
        tpm_engine_helper.write_to_nv_index(AUTH_VALUE, TPM_NV_INDEX_AIK_CERT, &ak_cert_input);
    assert!(result.is_ok(), "{result:?}");

    let result = tpm_engine_helper.allocate_guest_attestation_nv_indices(
        AUTH_VALUE,
        AllocateNvIndicesParams {
            preserve_ak_cert: true,
            support_attestation_report: true,
            mitigate_legacy_akcert: false,
            create_if_missing: true,
        },
    );
    assert!(result.is_ok(), "{result:?}");

    // The AK cert index is re-created at the default size and the previous cert
    // is dropped because it no longer fits.
    let result = tpm_engine_helper
        .find_nv_index(TPM_NV_INDEX_AIK_CERT)
        .expect("find_nv_index should succeed")
        .expect("AKCert NV index present");
    assert_eq!(
        result.nv_public.nv_public.data_size.get() as usize,
        TPM_DEFAULT_AKCERT_SIZE
    );

    let mut ak_cert_output = [0u8; TPM_DEFAULT_AKCERT_SIZE];
    let result = tpm_engine_helper.read_from_nv_index(TPM_NV_INDEX_AIK_CERT, &mut ak_cert_output);
    assert!(matches!(result.unwrap(), NvIndexState::Uninitialized));

    // The attestation report index is still allocated.
    let mut attestation_report_output = [0u8; MAX_ATTESTATION_INDEX_SIZE as usize];
    let result = tpm_engine_helper.read_from_nv_index(
        TPM_NV_INDEX_ATTESTATION_REPORT,
        &mut attestation_report_output,
    );
    assert!(matches!(result.unwrap(), NvIndexState::Uninitialized));
}
