# Copyright (c) Microsoft Corporation.
# Licensed under the MIT License.

[package]
name = "get_resources"
edition.workspace = true
rust-version.workspace = true

[dependencies]
ipmi_protocol.workspace = true
smbios_defs.workspace = true

vm_resource.workspace = true
vmgs_resources.workspace = true
mesh.workspace = true
inspect.workspace = true

thiserror.workspace = true

[lints]
workspace = true
