// Copyright (c) Microsoft Corporation.
// Licensed under the MIT License.

//! Common definitions for VM configuration and events

/// Firmware events generated by the guest.
#[derive(Debug, PartialEq, Eq, Copy, Clone)]
#[cfg_attr(feature = "mesh", derive(mesh_protobuf::Protobuf))]
pub enum FirmwareEvent {
    /// Boot was successful.
    BootSuccess,
    /// Boot failed.
    BootFailed,
    /// No boot device could be found.
    NoBootDevice,
    /// A boot attempt was made.
    BootAttempt,
}

/// Guest state lifetime
#[derive(Clone, Debug, Copy, Default)]
#[cfg_attr(feature = "mesh", derive(mesh_protobuf::Protobuf))]
pub enum GuestStateLifetime {
    /// Use the file or GED-backed VMGS and fail if it is corrupted.
    #[default]
    Default,
    /// Use the file or GED-backed VMGS and reformat if it is corrupted.
    ClearOnFailure,
    /// Reformat and use the file or GED-backed VMGS.
    Clear,
    /// Store guest state in memory
    Ephemeral,
}
