# Copyright (c) Microsoft Corporation.
# Licensed under the MIT License.

[package]
name = "ipmi_kcs"
edition.workspace = true
rust-version.workspace = true

[dependencies]
chipset_device.workspace = true
chipset_device_resources.workspace = true
chipset_resources.workspace = true
inspect.workspace = true
ipmi_protocol.workspace = true
local_clock = { workspace = true, features = ["inspect"] }
mesh.workspace = true
thiserror.workspace = true
vm_resource.workspace = true
vmcore.workspace = true
zerocopy.workspace = true

async-trait.workspace = true

[dev-dependencies]
parking_lot.workspace = true
test_with_tracing.workspace = true

[lints]
workspace = true
